### ISSUE TITLE
Incorrect of invisible space for some words

### ISSUE THREAD

**Issue by channakchhon** [passerelles-numeriques/khmer-typing#2]
Some word like "សំណា​​ល" the invisible happens at "សំណា​​" which is not the complete word yet.

**Comment by HennequinLaura** [comment]
Thank you for catching this. For this version I just used a short paragraph from an article I found online, but for the next version we'll use more reliable sources.

**Comment by bbalet** [comment]
Some good sources here: https://wapatoa.com/km/

**Comment by bbalet** [comment]
Fixed by https://github.com/passerelles-numeriques/khmer-typing/commit/a2018cfe47f3ce84ed4cd57d66b75f5e1990974a
